# Generated by Django 5.2 on 2025-09-28 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('middle', 'Middle'), ('high', 'High')], default='low', max_length=100)),
                ('subject', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('max_reply_date', models.DateTimeField(help_text='the maximum reply')),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('tracking_code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tickets.category')),
                ('tags', models.ManyToManyField(blank=True, related_name='tickets', to='tickets.tag')),
            ],
            options={
                'db_table': 'tickets-ticket',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('seen_at', models.DateTimeField(blank=True, help_text='When this assignment was seen by assignee?}', null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('in-progress', 'In Progress'), ('solved', 'Solved'), ('impossible', 'Impossible')], default='new', max_length=15)),
                ('description', models.TextField(blank=True)),
                ('assignee', models.ForeignKey(help_text='User to whom this assignment was assigned', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL)),
                ('assigned_ticket', models.ForeignKey(help_text='Ticket to assign', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='tickets.ticket')),
            ],
            options={
                'db_table': 'assignment',
            },
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['category'], name='tickets-tic_categor_6da903_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['priority'], name='tickets-tic_priorit_20830f_idx'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.UniqueConstraint(fields=('assigned_ticket', 'assignee'), name='unique_ticket_assignee'),
        ),
    ]
